# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/BenCarter/Documents/Bens Work/Coding/C++/PrettyConsole"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/BenCarter/Documents/Bens Work/Coding/C++/PrettyConsole"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/BenCarter/Documents/Bens Work/Coding/C++/PrettyConsole/CMakeFiles" "/mnt/c/Users/BenCarter/Documents/Bens Work/Coding/C++/PrettyConsole/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/BenCarter/Documents/Bens Work/Coding/C++/PrettyConsole/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PrettyConsole

# Build rule for target.
PrettyConsole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrettyConsole
.PHONY : PrettyConsole

# fast build rule for target.
PrettyConsole/fast:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/build
.PHONY : PrettyConsole/fast

PrettyConsole.o: PrettyConsole.cpp.o

.PHONY : PrettyConsole.o

# target to build an object file
PrettyConsole.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/PrettyConsole.cpp.o
.PHONY : PrettyConsole.cpp.o

PrettyConsole.i: PrettyConsole.cpp.i

.PHONY : PrettyConsole.i

# target to preprocess a source file
PrettyConsole.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/PrettyConsole.cpp.i
.PHONY : PrettyConsole.cpp.i

PrettyConsole.s: PrettyConsole.cpp.s

.PHONY : PrettyConsole.s

# target to generate assembly for a file
PrettyConsole.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/PrettyConsole.cpp.s
.PHONY : PrettyConsole.cpp.s

console.o: console.cpp.o

.PHONY : console.o

# target to build an object file
console.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/console.cpp.o
.PHONY : console.cpp.o

console.i: console.cpp.i

.PHONY : console.i

# target to preprocess a source file
console.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/console.cpp.i
.PHONY : console.cpp.i

console.s: console.cpp.s

.PHONY : console.s

# target to generate assembly for a file
console.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/console.cpp.s
.PHONY : console.cpp.s

line.o: line.cpp.o

.PHONY : line.o

# target to build an object file
line.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/line.cpp.o
.PHONY : line.cpp.o

line.i: line.cpp.i

.PHONY : line.i

# target to preprocess a source file
line.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/line.cpp.i
.PHONY : line.cpp.i

line.s: line.cpp.s

.PHONY : line.s

# target to generate assembly for a file
line.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/line.cpp.s
.PHONY : line.cpp.s

point.o: point.cpp.o

.PHONY : point.o

# target to build an object file
point.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/point.cpp.o
.PHONY : point.cpp.o

point.i: point.cpp.i

.PHONY : point.i

# target to preprocess a source file
point.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/point.cpp.i
.PHONY : point.cpp.i

point.s: point.cpp.s

.PHONY : point.s

# target to generate assembly for a file
point.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/point.cpp.s
.PHONY : point.cpp.s

rectangle.o: rectangle.cpp.o

.PHONY : rectangle.o

# target to build an object file
rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/rectangle.cpp.o
.PHONY : rectangle.cpp.o

rectangle.i: rectangle.cpp.i

.PHONY : rectangle.i

# target to preprocess a source file
rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/rectangle.cpp.i
.PHONY : rectangle.cpp.i

rectangle.s: rectangle.cpp.s

.PHONY : rectangle.s

# target to generate assembly for a file
rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/rectangle.cpp.s
.PHONY : rectangle.cpp.s

row.o: row.cpp.o

.PHONY : row.o

# target to build an object file
row.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/row.cpp.o
.PHONY : row.cpp.o

row.i: row.cpp.i

.PHONY : row.i

# target to preprocess a source file
row.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/row.cpp.i
.PHONY : row.cpp.i

row.s: row.cpp.s

.PHONY : row.s

# target to generate assembly for a file
row.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/row.cpp.s
.PHONY : row.cpp.s

screenComponent.o: screenComponent.cpp.o

.PHONY : screenComponent.o

# target to build an object file
screenComponent.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/screenComponent.cpp.o
.PHONY : screenComponent.cpp.o

screenComponent.i: screenComponent.cpp.i

.PHONY : screenComponent.i

# target to preprocess a source file
screenComponent.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/screenComponent.cpp.i
.PHONY : screenComponent.cpp.i

screenComponent.s: screenComponent.cpp.s

.PHONY : screenComponent.s

# target to generate assembly for a file
screenComponent.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/screenComponent.cpp.s
.PHONY : screenComponent.cpp.s

styleAttribute.o: styleAttribute.cpp.o

.PHONY : styleAttribute.o

# target to build an object file
styleAttribute.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/styleAttribute.cpp.o
.PHONY : styleAttribute.cpp.o

styleAttribute.i: styleAttribute.cpp.i

.PHONY : styleAttribute.i

# target to preprocess a source file
styleAttribute.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/styleAttribute.cpp.i
.PHONY : styleAttribute.cpp.i

styleAttribute.s: styleAttribute.cpp.s

.PHONY : styleAttribute.s

# target to generate assembly for a file
styleAttribute.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/styleAttribute.cpp.s
.PHONY : styleAttribute.cpp.s

styles.o: styles.cpp.o

.PHONY : styles.o

# target to build an object file
styles.cpp.o:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/styles.cpp.o
.PHONY : styles.cpp.o

styles.i: styles.cpp.i

.PHONY : styles.i

# target to preprocess a source file
styles.cpp.i:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/styles.cpp.i
.PHONY : styles.cpp.i

styles.s: styles.cpp.s

.PHONY : styles.s

# target to generate assembly for a file
styles.cpp.s:
	$(MAKE) -f CMakeFiles/PrettyConsole.dir/build.make CMakeFiles/PrettyConsole.dir/styles.cpp.s
.PHONY : styles.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... PrettyConsole"
	@echo "... edit_cache"
	@echo "... PrettyConsole.o"
	@echo "... PrettyConsole.i"
	@echo "... PrettyConsole.s"
	@echo "... console.o"
	@echo "... console.i"
	@echo "... console.s"
	@echo "... line.o"
	@echo "... line.i"
	@echo "... line.s"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
	@echo "... rectangle.o"
	@echo "... rectangle.i"
	@echo "... rectangle.s"
	@echo "... row.o"
	@echo "... row.i"
	@echo "... row.s"
	@echo "... screenComponent.o"
	@echo "... screenComponent.i"
	@echo "... screenComponent.s"
	@echo "... styleAttribute.o"
	@echo "... styleAttribute.i"
	@echo "... styleAttribute.s"
	@echo "... styles.o"
	@echo "... styles.i"
	@echo "... styles.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

